// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _03_Diyet.DataAccessLayer;

#nullable disable

namespace _03_Diyet.DataAccessLayer.Migrations
{
    [DbContext(typeof(DiyetDbContext))]
    partial class DiyetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_04_Diyet.DATA.Besin", b =>
                {
                    b.Property<int>("BesinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BesinId"));

                    b.Property<double>("KaloriMiktarı")
                        .HasColumnType("float");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("İsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BesinId");

                    b.HasIndex("KategoriId");

                    b.ToTable("Besinler");

                    b.HasData(
                        new
                        {
                            BesinId = 1,
                            KaloriMiktarı = 2.0,
                            KategoriId = 5,
                            Resim = "köfte.jpg",
                            İsmi = "Köfte"
                        },
                        new
                        {
                            BesinId = 2,
                            KaloriMiktarı = 2.0,
                            KategoriId = 7,
                            Resim = "tavuk.jpg",
                            İsmi = "Tavuk Izgara"
                        },
                        new
                        {
                            BesinId = 3,
                            KaloriMiktarı = 4.0,
                            KategoriId = 6,
                            Resim = "baklava.jpg",
                            İsmi = "Baklava"
                        },
                        new
                        {
                            BesinId = 4,
                            KaloriMiktarı = 2.0,
                            KategoriId = 5,
                            Resim = "misketkofte.jpg",
                            İsmi = "Misket Köfte"
                        },
                        new
                        {
                            BesinId = 5,
                            KaloriMiktarı = 1.3,
                            KategoriId = 13,
                            Resim = "pirincPilavi.jpg",
                            İsmi = "Pirinç Pilavı"
                        },
                        new
                        {
                            BesinId = 6,
                            KaloriMiktarı = 1.0,
                            KategoriId = 12,
                            Resim = "yogurt.jpg",
                            İsmi = "Yoğurt"
                        },
                        new
                        {
                            BesinId = 7,
                            KaloriMiktarı = 1.0,
                            KategoriId = 3,
                            Resim = "elma.jpg",
                            İsmi = "Elma"
                        },
                        new
                        {
                            BesinId = 8,
                            KaloriMiktarı = 1.0,
                            KategoriId = 4,
                            Resim = "havuc.jpg",
                            İsmi = "Havuç"
                        },
                        new
                        {
                            BesinId = 9,
                            KaloriMiktarı = 2.0,
                            KategoriId = 1,
                            Resim = "korisoslumakarna.jpg",
                            İsmi = "Köri Soslu Makarna"
                        },
                        new
                        {
                            BesinId = 10,
                            KaloriMiktarı = 2.5,
                            KategoriId = 10,
                            Resim = "mantı.jpg",
                            İsmi = "Mantı"
                        },
                        new
                        {
                            BesinId = 11,
                            KaloriMiktarı = 1.0,
                            KategoriId = 8,
                            Resim = "firinda-mantarli-karides.jpg",
                            İsmi = "Fırında Mantarlı Karides"
                        },
                        new
                        {
                            BesinId = 12,
                            KaloriMiktarı = 3.0,
                            KategoriId = 5,
                            Resim = "hamburger.jpg",
                            İsmi = "Hamburger"
                        },
                        new
                        {
                            BesinId = 13,
                            KaloriMiktarı = 3.0,
                            KategoriId = 4,
                            Resim = "patatesKizartmasi.jpg",
                            İsmi = "Patates Kızartması"
                        },
                        new
                        {
                            BesinId = 14,
                            KaloriMiktarı = 1.0,
                            KategoriId = 10,
                            Resim = "sigaraBoregi.jpg",
                            İsmi = "Sigara Böreği"
                        },
                        new
                        {
                            BesinId = 15,
                            KaloriMiktarı = 2.7999999999999998,
                            KategoriId = 10,
                            Resim = "beyazEkmekkkkkkk.jpg",
                            İsmi = "Beyaz Ekmek"
                        },
                        new
                        {
                            BesinId = 16,
                            KaloriMiktarı = 3.0,
                            KategoriId = 10,
                            Resim = "pizza.jpg",
                            İsmi = "Pizza"
                        },
                        new
                        {
                            BesinId = 17,
                            KaloriMiktarı = 3.7999999999999998,
                            KategoriId = 12,
                            Resim = "beyazPeynir.jpg",
                            İsmi = "Beyaz Peynir"
                        },
                        new
                        {
                            BesinId = 18,
                            KaloriMiktarı = 3.5,
                            KategoriId = 1,
                            Resim = "makarna.jpg",
                            İsmi = "Makarna"
                        },
                        new
                        {
                            BesinId = 19,
                            KaloriMiktarı = 8.8000000000000007,
                            KategoriId = 4,
                            Resim = "zeytinyagiiiii.jpg",
                            İsmi = "Zeytinyağı"
                        },
                        new
                        {
                            BesinId = 20,
                            KaloriMiktarı = 7.0999999999999996,
                            KategoriId = 3,
                            Resim = "hindistanCeviz.jpg",
                            İsmi = "Hindistan Cevizi"
                        },
                        new
                        {
                            BesinId = 21,
                            KaloriMiktarı = 0.20000000000000001,
                            KategoriId = 4,
                            Resim = "kirmiziBiber.jpg",
                            İsmi = "Kırmızı Biber"
                        },
                        new
                        {
                            BesinId = 22,
                            KaloriMiktarı = 2.0,
                            KategoriId = 8,
                            Resim = "somonfiletoBalik.jpg",
                            İsmi = "Somon Balığı"
                        },
                        new
                        {
                            BesinId = 23,
                            KaloriMiktarı = 6.0,
                            KategoriId = 6,
                            Resim = "fistik ezmesi.jpg",
                            İsmi = "Fıstık Ezmesi"
                        },
                        new
                        {
                            BesinId = 24,
                            KaloriMiktarı = 0.29999999999999999,
                            KategoriId = 3,
                            Resim = "cilek.jpg",
                            İsmi = "Çilek"
                        },
                        new
                        {
                            BesinId = 25,
                            KaloriMiktarı = 0.29999999999999999,
                            KategoriId = 4,
                            Resim = "brokoli.jpg",
                            İsmi = "Brokoli"
                        },
                        new
                        {
                            BesinId = 26,
                            KaloriMiktarı = 0.20000000000000001,
                            KategoriId = 4,
                            Resim = "kabakpismis.jpg",
                            İsmi = "Kabak"
                        },
                        new
                        {
                            BesinId = 27,
                            KaloriMiktarı = 0.5,
                            KategoriId = 3,
                            Resim = "ananas.jpg",
                            İsmi = "Ananas"
                        },
                        new
                        {
                            BesinId = 28,
                            KaloriMiktarı = 1.0,
                            KategoriId = 4,
                            Resim = "pirasaYemegi.jpg",
                            İsmi = "Pırasa yemeği"
                        },
                        new
                        {
                            BesinId = 29,
                            KaloriMiktarı = 4.0,
                            KategoriId = 10,
                            Resim = "kiymaliBorek.jpg",
                            İsmi = "Kıymalı Börek"
                        },
                        new
                        {
                            BesinId = 30,
                            KaloriMiktarı = 0.5,
                            KategoriId = 12,
                            Resim = "suzmeYogurt.jpg",
                            İsmi = "Süzme Yoğurt"
                        },
                        new
                        {
                            BesinId = 31,
                            KaloriMiktarı = 3.7999999999999998,
                            KategoriId = 2,
                            Resim = "kahvaltilikgevrek.jpg",
                            İsmi = "Kahvaltılık Gevrek"
                        },
                        new
                        {
                            BesinId = 32,
                            KaloriMiktarı = 5.5,
                            KategoriId = 6,
                            Resim = "cikolata.jpg",
                            İsmi = "Çikolata"
                        },
                        new
                        {
                            BesinId = 33,
                            KaloriMiktarı = 1.0,
                            KategoriId = 11,
                            Resim = "cobanSalata.jpg",
                            İsmi = "Çoban Salatası"
                        },
                        new
                        {
                            BesinId = 34,
                            KaloriMiktarı = 1.0,
                            KategoriId = 9,
                            Resim = "yesilMercoCorbasi.jpg",
                            İsmi = "Yeşil Mercimek Çorbası"
                        },
                        new
                        {
                            BesinId = 35,
                            KaloriMiktarı = 3.0,
                            KategoriId = 4,
                            Resim = "kumpir.jpg",
                            İsmi = "Kumpir"
                        },
                        new
                        {
                            BesinId = 36,
                            KaloriMiktarı = 1.0,
                            KategoriId = 4,
                            Resim = "zeytoEnginar,.jpg",
                            İsmi = "Zeytinyağlı Enginar"
                        },
                        new
                        {
                            BesinId = 37,
                            KaloriMiktarı = 1.0,
                            KategoriId = 2,
                            Resim = "portokalliMeyveSuyu.jpg",
                            İsmi = "Portakal Suyu"
                        },
                        new
                        {
                            BesinId = 38,
                            KaloriMiktarı = 1.3,
                            KategoriId = 9,
                            Resim = "kremaliSebzeCorbasi.jpg",
                            İsmi = "Kremalı Sebze Çorbası"
                        },
                        new
                        {
                            BesinId = 39,
                            KaloriMiktarı = 1.0,
                            KategoriId = 4,
                            Resim = "tazeFasulye.jpg",
                            İsmi = "Taze Fasulye"
                        },
                        new
                        {
                            BesinId = 40,
                            KaloriMiktarı = 1.0,
                            KategoriId = 12,
                            Resim = "zeytinEzmeliCıtırEkmek.jpg",
                            İsmi = "Kefir"
                        },
                        new
                        {
                            BesinId = 41,
                            KaloriMiktarı = 3.0,
                            KategoriId = 10,
                            Resim = "zeytinEzmeliCıtırEkmek.jpg",
                            İsmi = "Zeytin Ezmeli Çıtır Ekmek"
                        },
                        new
                        {
                            BesinId = 42,
                            KaloriMiktarı = 1.0,
                            KategoriId = 11,
                            Resim = "makarnaSalatası.jpg",
                            İsmi = "Makarna Salatası"
                        },
                        new
                        {
                            BesinId = 43,
                            KaloriMiktarı = 0.25,
                            KategoriId = 4,
                            Resim = "karnabaharYemegi.jpg",
                            İsmi = "Karnabahar"
                        },
                        new
                        {
                            BesinId = 44,
                            KaloriMiktarı = 2.5,
                            KategoriId = 5,
                            Resim = "KuzuEti.jpg",
                            İsmi = "Kuzu Eti"
                        },
                        new
                        {
                            BesinId = 45,
                            KaloriMiktarı = 2.2000000000000002,
                            KategoriId = 7,
                            Resim = "tavukSis.jpg",
                            İsmi = "Tavuk Şiş"
                        },
                        new
                        {
                            BesinId = 46,
                            KaloriMiktarı = 2.0,
                            KategoriId = 8,
                            Resim = "levrek.jpg",
                            İsmi = "Levrek"
                        },
                        new
                        {
                            BesinId = 47,
                            KaloriMiktarı = 1.5,
                            KategoriId = 13,
                            Resim = "sarayPilavi.jpg",
                            İsmi = "Saray Pilavı"
                        },
                        new
                        {
                            BesinId = 48,
                            KaloriMiktarı = 2.2000000000000002,
                            KategoriId = 5,
                            Resim = "Biftek.jpg",
                            İsmi = "Biftek"
                        },
                        new
                        {
                            BesinId = 49,
                            KaloriMiktarı = 3.0,
                            KategoriId = 1,
                            Resim = "penneArabiata.jpg",
                            İsmi = "Penne Arrabbiata"
                        },
                        new
                        {
                            BesinId = 50,
                            KaloriMiktarı = 4.5,
                            KategoriId = 6,
                            Resim = "profiterol.jpg",
                            İsmi = "Profiterol"
                        },
                        new
                        {
                            BesinId = 51,
                            KaloriMiktarı = 2.2999999999999998,
                            KategoriId = 7,
                            Resim = "tavukKanat.jpg",
                            İsmi = "Tavuk Kanat"
                        },
                        new
                        {
                            BesinId = 52,
                            KaloriMiktarı = 1.8999999999999999,
                            KategoriId = 8,
                            Resim = "sardalya.jpg",
                            İsmi = "Sardalya"
                        },
                        new
                        {
                            BesinId = 53,
                            KaloriMiktarı = 1.5,
                            KategoriId = 9,
                            Resim = "mercoCorbasiii.jpg",
                            İsmi = "Mercimek Çorbası"
                        },
                        new
                        {
                            BesinId = 54,
                            KaloriMiktarı = 1.7,
                            KategoriId = 11,
                            Resim = "kinoaSalatasi.jpg",
                            İsmi = "Kinoa Salatası"
                        },
                        new
                        {
                            BesinId = 55,
                            KaloriMiktarı = 1.5,
                            KategoriId = 4,
                            Resim = "kabakMucver.jpg",
                            İsmi = "Kabak Mücver"
                        },
                        new
                        {
                            BesinId = 56,
                            KaloriMiktarı = 2.0,
                            KategoriId = 4,
                            Resim = "tahinliKabakTatlis.jpg",
                            İsmi = "Tahinli Kabak Tatlısı"
                        },
                        new
                        {
                            BesinId = 57,
                            KaloriMiktarı = 1.8,
                            KategoriId = 4,
                            Resim = "biberDolmasii.jpg",
                            İsmi = "Biber Dolması"
                        },
                        new
                        {
                            BesinId = 58,
                            KaloriMiktarı = 3.0,
                            KategoriId = 6,
                            Resim = "dondurmaa.jpg",
                            İsmi = "Dondurma"
                        },
                        new
                        {
                            BesinId = 59,
                            KaloriMiktarı = 2.5,
                            KategoriId = 10,
                            Resim = "sushi.jpg",
                            İsmi = "Sushi"
                        },
                        new
                        {
                            BesinId = 60,
                            KaloriMiktarı = 4.0,
                            KategoriId = 6,
                            Resim = "havuclıtatlikek.jpg",
                            İsmi = "Havuçlu Kek"
                        },
                        new
                        {
                            BesinId = 61,
                            KaloriMiktarı = 1.0,
                            KategoriId = 13,
                            Resim = "bullgurPilavi.jpg",
                            İsmi = "Bulgur Pilavı"
                        },
                        new
                        {
                            BesinId = 62,
                            KaloriMiktarı = 2.0,
                            KategoriId = 11,
                            Resim = "avokadoSalatasi.jpg",
                            İsmi = "Avokado Salatası"
                        },
                        new
                        {
                            BesinId = 63,
                            KaloriMiktarı = 0.69999999999999996,
                            KategoriId = 2,
                            Resim = "sütlü kahve.jpg",
                            İsmi = "Sütlü Kahve"
                        },
                        new
                        {
                            BesinId = 64,
                            KaloriMiktarı = 2.0,
                            KategoriId = 6,
                            Resim = "trileçe.jpg",
                            İsmi = "Trileçe"
                        },
                        new
                        {
                            BesinId = 65,
                            KaloriMiktarı = 2.0,
                            KategoriId = 1,
                            Resim = "fettuciniAlfredo.jpg",
                            İsmi = "Fettuccine Alfredo"
                        },
                        new
                        {
                            BesinId = 66,
                            KaloriMiktarı = 2.0,
                            KategoriId = 6,
                            Resim = "sütlac.jpg",
                            İsmi = "Sütlaç"
                        },
                        new
                        {
                            BesinId = 67,
                            KaloriMiktarı = 1.6000000000000001,
                            KategoriId = 11,
                            Resim = "kısır.jpg",
                            İsmi = "Kısır"
                        },
                        new
                        {
                            BesinId = 68,
                            KaloriMiktarı = 2.7999999999999998,
                            KategoriId = 7,
                            Resim = "tavukSote.jpg",
                            İsmi = "Tavuk Sote"
                        },
                        new
                        {
                            BesinId = 69,
                            KaloriMiktarı = 2.5,
                            KategoriId = 4,
                            Resim = "kuruFasulye.jpg",
                            İsmi = "Kuru Fasulye"
                        },
                        new
                        {
                            BesinId = 70,
                            KaloriMiktarı = 3.0,
                            KategoriId = 4,
                            Resim = "patlıcanMusakka.jpg",
                            İsmi = "Patlıcan Musakka"
                        },
                        new
                        {
                            BesinId = 71,
                            KaloriMiktarı = 2.7000000000000002,
                            KategoriId = 5,
                            Resim = "etli nohut.jpg",
                            İsmi = "Etli Nohut"
                        },
                        new
                        {
                            BesinId = 72,
                            KaloriMiktarı = 1.5,
                            KategoriId = 4,
                            Resim = "FirindaPatates.jpg",
                            İsmi = "Fırında Patates"
                        },
                        new
                        {
                            BesinId = 73,
                            KaloriMiktarı = 1.3,
                            KategoriId = 9,
                            Resim = "yogurtCorbası.jpg",
                            İsmi = "Yoğurt Çorbası"
                        },
                        new
                        {
                            BesinId = 74,
                            KaloriMiktarı = 2.6000000000000001,
                            KategoriId = 8,
                            Resim = "hamsiTava.jpg",
                            İsmi = "Hamsi Tava"
                        },
                        new
                        {
                            BesinId = 75,
                            KaloriMiktarı = 3.1000000000000001,
                            KategoriId = 5,
                            Resim = "icliKöfte.jpg",
                            İsmi = "İçli Köfte"
                        },
                        new
                        {
                            BesinId = 76,
                            KaloriMiktarı = 1.5,
                            KategoriId = 6,
                            Resim = "muhallebi.jpg",
                            İsmi = "Muhallebi"
                        },
                        new
                        {
                            BesinId = 77,
                            KaloriMiktarı = 1.8,
                            KategoriId = 4,
                            Resim = "baklaliEnginarYemegi.jpg",
                            İsmi = "Baklalı Enginar"
                        },
                        new
                        {
                            BesinId = 78,
                            KaloriMiktarı = 2.3999999999999999,
                            KategoriId = 10,
                            Resim = "pacabgaBoregi.jpg",
                            İsmi = "Paçanga Böreği"
                        },
                        new
                        {
                            BesinId = 79,
                            KaloriMiktarı = 1.8999999999999999,
                            KategoriId = 1,
                            Resim = "eriste.jpg",
                            İsmi = "Erişte"
                        },
                        new
                        {
                            BesinId = 80,
                            KaloriMiktarı = 1.2,
                            KategoriId = 11,
                            Resim = "borulcesalatasi.jpg",
                            İsmi = "Taze Börülce Salatası"
                        },
                        new
                        {
                            BesinId = 81,
                            KaloriMiktarı = 3.0,
                            KategoriId = 5,
                            Resim = "karnıyarik.jpg",
                            İsmi = "Karnıyarık"
                        },
                        new
                        {
                            BesinId = 82,
                            KaloriMiktarı = 1.5,
                            KategoriId = 4,
                            Resim = "menemen.jpg",
                            İsmi = "Menemen"
                        },
                        new
                        {
                            BesinId = 83,
                            KaloriMiktarı = 1.8999999999999999,
                            KategoriId = 13,
                            Resim = "tavuklupilav.jpg",
                            İsmi = "Tavuklu Pilav"
                        },
                        new
                        {
                            BesinId = 84,
                            KaloriMiktarı = 1.2,
                            KategoriId = 11,
                            Resim = "patatesSalatasi.jpg",
                            İsmi = "Patates Salatası"
                        },
                        new
                        {
                            BesinId = 85,
                            KaloriMiktarı = 3.2000000000000002,
                            KategoriId = 6,
                            Resim = "sarayLokumu.jpg",
                            İsmi = "Saray Lokumu"
                        },
                        new
                        {
                            BesinId = 86,
                            KaloriMiktarı = 3.0,
                            KategoriId = 10,
                            Resim = "cızlak.jpg",
                            İsmi = "Cızlak"
                        },
                        new
                        {
                            BesinId = 87,
                            KaloriMiktarı = 1.5,
                            KategoriId = 12,
                            Resim = "cılbır.jpg",
                            İsmi = "Çılbır"
                        },
                        new
                        {
                            BesinId = 88,
                            KaloriMiktarı = 1.8999999999999999,
                            KategoriId = 1,
                            Resim = "tavuklımakarna.jpg",
                            İsmi = "Tavuklu Makarna"
                        },
                        new
                        {
                            BesinId = 89,
                            KaloriMiktarı = 2.6000000000000001,
                            KategoriId = 10,
                            Resim = "avciBoregi.jpg",
                            İsmi = "Avcı Böreği"
                        },
                        new
                        {
                            BesinId = 90,
                            KaloriMiktarı = 1.2,
                            KategoriId = 4,
                            Resim = "firindaMantar.jpg",
                            İsmi = "Fırında Mantar"
                        },
                        new
                        {
                            BesinId = 91,
                            KaloriMiktarı = 1.0,
                            KategoriId = 11,
                            Resim = "havucTarator.jpg",
                            İsmi = "Havuç Tarator"
                        },
                        new
                        {
                            BesinId = 92,
                            KaloriMiktarı = 2.0,
                            KategoriId = 10,
                            Resim = "peynirliKrep.jpg",
                            İsmi = "Peynirli Krep"
                        },
                        new
                        {
                            BesinId = 93,
                            KaloriMiktarı = 1.3,
                            KategoriId = 4,
                            Resim = "barbunyaPilaki.jpg",
                            İsmi = "Barbunya Pilaki"
                        },
                        new
                        {
                            BesinId = 94,
                            KaloriMiktarı = 3.5,
                            KategoriId = 10,
                            Resim = "tahinliPide.jpg",
                            İsmi = "Tahinli Pide"
                        },
                        new
                        {
                            BesinId = 95,
                            KaloriMiktarı = 3.3999999999999999,
                            KategoriId = 6,
                            Resim = "İrmikHelvasi.jpg",
                            İsmi = "İrmik Helvası"
                        },
                        new
                        {
                            BesinId = 96,
                            KaloriMiktarı = 1.7,
                            KategoriId = 11,
                            Resim = "mercimekKoftesi.jpg",
                            İsmi = "Mercimek Köftesi"
                        },
                        new
                        {
                            BesinId = 97,
                            KaloriMiktarı = 1.2,
                            KategoriId = 9,
                            Resim = "yaylacorbasiNohutlu.jpg",
                            İsmi = "Nohutlu Yayla Çorbası"
                        },
                        new
                        {
                            BesinId = 98,
                            KaloriMiktarı = 1.3999999999999999,
                            KategoriId = 4,
                            Resim = "karnabaharGraten.jpg",
                            İsmi = "Karnabahar Graten"
                        },
                        new
                        {
                            BesinId = 99,
                            KaloriMiktarı = 2.1000000000000001,
                            KategoriId = 8,
                            Resim = "tereyağliKarides.jpg",
                            İsmi = "Tereyağlı Karides"
                        },
                        new
                        {
                            BesinId = 100,
                            KaloriMiktarı = 0.25,
                            KategoriId = 11,
                            Resim = "yogurtlusemizosuSalatasi.jpg",
                            İsmi = "Yoğurtlu Semizotu Salatası"
                        });
                });

            modelBuilder.Entity("_04_Diyet.DATA.BesinKategori", b =>
                {
                    b.Property<int>("BesinKategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BesinKategoriId"));

                    b.Property<string>("İsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BesinKategoriId");

                    b.ToTable("BesinKategorileri");

                    b.HasData(
                        new
                        {
                            BesinKategoriId = 1,
                            İsmi = "Makarnalar"
                        },
                        new
                        {
                            BesinKategoriId = 2,
                            İsmi = "İçecekler"
                        },
                        new
                        {
                            BesinKategoriId = 3,
                            İsmi = "Meyveler"
                        },
                        new
                        {
                            BesinKategoriId = 4,
                            İsmi = "Sebzeler"
                        },
                        new
                        {
                            BesinKategoriId = 5,
                            İsmi = "Et Ürünleri"
                        },
                        new
                        {
                            BesinKategoriId = 6,
                            İsmi = "Tatlılar"
                        },
                        new
                        {
                            BesinKategoriId = 7,
                            İsmi = "Tavuk Ürünleri"
                        },
                        new
                        {
                            BesinKategoriId = 8,
                            İsmi = "Balık Ürünleri"
                        },
                        new
                        {
                            BesinKategoriId = 9,
                            İsmi = "Çorbalar"
                        },
                        new
                        {
                            BesinKategoriId = 10,
                            İsmi = "Unlu Mamuller"
                        },
                        new
                        {
                            BesinKategoriId = 11,
                            İsmi = "Salatalar"
                        },
                        new
                        {
                            BesinKategoriId = 12,
                            İsmi = "Süt Ve Süt Ürünleri"
                        },
                        new
                        {
                            BesinKategoriId = 13,
                            İsmi = "Pilavlar"
                        });
                });

            modelBuilder.Entity("_04_Diyet.DATA.KaloriVeri", b =>
                {
                    b.Property<int>("KaloriVeriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KaloriVeriId"));

                    b.Property<int>("BesinId")
                        .HasColumnType("int");

                    b.Property<int>("Kalori")
                        .HasColumnType("int");

                    b.Property<DateTime>("OluşturulmaTarihi")
                        .HasColumnType("date");

                    b.Property<int>("ProfilId")
                        .HasColumnType("int");

                    b.Property<int>("ÖğünId")
                        .HasColumnType("int");

                    b.HasKey("KaloriVeriId");

                    b.HasIndex("BesinId");

                    b.HasIndex("ProfilId");

                    b.HasIndex("ÖğünId");

                    b.ToTable("KaloriVeriTakip");
                });

            modelBuilder.Entity("_04_Diyet.DATA.Profil", b =>
                {
                    b.Property<int>("ProfilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfilId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Boy")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DoğumTarihi")
                        .HasColumnType("date");

                    b.Property<int>("Kilo")
                        .HasColumnType("int");

                    b.Property<string>("KullanıcıEposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProfilOluşturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Şifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfilId");

                    b.ToTable("Profiller");
                });

            modelBuilder.Entity("_04_Diyet.DATA.Öğün", b =>
                {
                    b.Property<int>("ÖğünId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ÖğünId"));

                    b.Property<string>("İsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ÖğünId");

                    b.ToTable("Öğünler");

                    b.HasData(
                        new
                        {
                            ÖğünId = 1,
                            İsmi = "Kahvaltı"
                        },
                        new
                        {
                            ÖğünId = 2,
                            İsmi = "Öğle Yemeği"
                        },
                        new
                        {
                            ÖğünId = 3,
                            İsmi = "Akşam Yemeği"
                        },
                        new
                        {
                            ÖğünId = 4,
                            İsmi = "Aperatifler"
                        });
                });

            modelBuilder.Entity("_04_Diyet.DATA.Besin", b =>
                {
                    b.HasOne("_04_Diyet.DATA.BesinKategori", "Kategori")
                        .WithMany("Besinler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("_04_Diyet.DATA.KaloriVeri", b =>
                {
                    b.HasOne("_04_Diyet.DATA.Besin", "Besin")
                        .WithMany("KaloriVerileri")
                        .HasForeignKey("BesinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_04_Diyet.DATA.Profil", "Profil")
                        .WithMany("KaloriVerileri")
                        .HasForeignKey("ProfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_04_Diyet.DATA.Öğün", "Öğün")
                        .WithMany("KaloriVerileri")
                        .HasForeignKey("ÖğünId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Besin");

                    b.Navigation("Profil");

                    b.Navigation("Öğün");
                });

            modelBuilder.Entity("_04_Diyet.DATA.Besin", b =>
                {
                    b.Navigation("KaloriVerileri");
                });

            modelBuilder.Entity("_04_Diyet.DATA.BesinKategori", b =>
                {
                    b.Navigation("Besinler");
                });

            modelBuilder.Entity("_04_Diyet.DATA.Profil", b =>
                {
                    b.Navigation("KaloriVerileri");
                });

            modelBuilder.Entity("_04_Diyet.DATA.Öğün", b =>
                {
                    b.Navigation("KaloriVerileri");
                });
#pragma warning restore 612, 618
        }
    }
}
